[metadata]
description-file = 'README.md'

[build-system]
requires = ["setuptools>=46.0", "wheel>=0.34"]

[tox]
envlist = 'py37,py38'

[testenv]
whitelist_externals = ['poetry']
skipdist = true
deps = ["pytest", "hypothesis", "wheel"]
commands = ["pytest", "python setup.py sdist bdist_wheel"]

[tool.poetry]
name = "tyrannosaurus"
version = "0.0.1"
description = ""
authors = ["Douglas Myers-Turnbull"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.7"

[mypy]
check_untyped_defs = true
strict_optional = true

[tool.black]
line-length = 100
target-version = ['py37', 'py38']

[flake8]
max-line-length = 100
doctests = true
exclude =  ['.git', '__pycache__', 'build/', 'dist/']

[pycodestyle]
max-line-length = 100
statistics = true

[pydocstyle]
# 212 and 213 contradict; 203 and 204 contradict; D302 is not relevant in Py3
ignore = ['D203', 'D212', 'D302']

[tool.isort]
line_length = 100
