
[build-system]
requires = ["setuptools>=46.1", "wheel>=0.34"]

[tox]
envlist = 'py37,py38'

[testenv]
skipdist=True
deps = ["pytest", "hypothesis", "wheel"]
commands = ["pytest", "python setup.py sdist bdist_wheel"]

[tool.poetry]
name = "tyrannosaurus"
version = "0.0.1"
description = ""
authors = ["Douglas Myers-Turnbull"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.7"
