[build-system]
requires = ["setuptools>=46.1", "wheel>=0.34"]

[tox]
envlist = 'py37,py38'

[testenv]
whitelist_externals = poetry
skipdist = true
deps = ["pytest", "hypothesis", "wheel"]
commands = ["pytest", "python setup.py sdist bdist_wheel"]

[tool.poetry]
name = "tyrannosaurus"
version = "0.0.1"
description = ""
authors = ["Douglas Myers-Turnbull"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.7"

[flake8]
max-line-length = 120

[tool.black]
line-length = 120
target-version = ['py37', 'py38']

[tool.isort]
line_length = 120
