name: Test and update badges on push to main
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version:
          # from tyrannosaurus "pymetaversion"; actual versions are handled in Tox
          - 3.9
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: python
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade virtualenv
          pip install tox
      - name: Test with tox
        run: |
          tox -v
      - name: Build the Docker image
        run: |
          docker build .
      - name: Update coveralls/codecov
        run: |
          pip install coveralls codecov
          coveralls
          codecov
      - name: Run Github CodeQL
        uses: github/codeql-action/analyze@v1
